### PR TITLE
Revised footer

### PR DESCRIPTION
**Pull request by rlskoeser**
review the footer on desktop and mobile on the preview site:
https://lenape-timetree-dev-pr-3.onrender.com/

### CODE REVIEW

**Comment by mnaydan** [comment]
@rlskoeser mobile looks terrific. Desktop across browsers looks pretty good too, just a couple issues:

Even when my window is pretty much full size, the "with" in "In collaboration with" gets cut off at the bottom:
Screenshot 2023-10-31 at 4 33 31 PM

When the window is even smaller (basically right before it snaps to "mobile"), it cuts off the Princeton logo & trustees line on the right. I don't think that's as big of an issue, it's hard to fit them all as the window gets smaller, but thought I'd flag it since those logos are responding differently from the department logos, which minimize in size as the window decreases.
Screenshot 2023-10-31 at 4 35 45 PM

**Comment by rlskoeser** [comment]
@mnaydan thanks for testing. Can you give me the screen resolution where the in collaboration text is wrapping?

**Comment by mnaydan** [comment]
@rlskoeser I think it's wrapping starting when the footer is 1335x106, does that seem right?

**Comment by rlskoeser** [comment]
@mnaydan thank you! I've thought of what I hope is a simple way to handle it - I'll just set a min-width so it never gets shorter than the size needed to display "in collaboration" on one line.  

Question for when it wraps: does right aligned or left aligned look better?
Screenshot 2023-10-31 at 5 06 35 PM
Screenshot 2023-10-31 at 5 06 59 PM

**Comment by mnaydan** [comment]
@rlskoeser that makes sense! I want to say left aligned looks better to my eye?

**Comment by rlskoeser** [comment]
@mnaydan thanks! I trust your eye. Pushing a tweak to the styles, should be visible on the render PR site after a bit.

**Comment by mnaydan** [comment]
@rlskoeser that seems to have fixed the wrapping issue! Looks great!

**Pull request closed without merging**
